name: Build and Deploy Docusaurus

on:
  push:
    paths:
      - 'docs/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docusaurus
      run: npm run build

    - name: Deploy to main
      if: github.ref != 'refs/heads/main'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'actions@github.com'
        git checkout main
        git pull origin main
        rm -rf build/
        mv ./build/ ./new_build/
        git add -A
        git commit -m "Auto-build and deploy Docusaurus site [skip ci]"
        git push origin main
